name: Unit Tests with PyTest 

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install venv
        run: |
          python -m venv lSystem-venv
          
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          
      - name: Run pytest 
        run: |
          pytest 
